resource-manager: bypass command_special_processing when session is p…
tpm2-software/tpm2-abrmd pull request #819
Opened 2022-10-15 22:11 UTC by whooo

…rovided

TPM2_GetCapability accepts an audit session, when specified no special processing should be done.
If a session without the audit flag set is passed let the TPM handle the error.

2022-10-21 15:58 UTC, williamcroberts requested changes

2022-10-21 15:58 UTC, williamcroberts commented on src/resource-manager.c
> +    switch (cc) {
I would prefer we keep the handling of commands within the respective switch statement for the command code, and thus would prefer something like:
```diff
diff --git a/src/resource-manager.c b/src/resource-manager.c
index 6459b1f409e6..45fb36bb99a8 100644
--- a/src/resource-manager.c
+++ b/src/resource-manager.c
@@ -1121,8 +1121,10 @@ command_special_processing (ResourceManager *resmgr,
         response = resource_manager_load_context (resmgr, command);
         break;
     case TPM2_CC_GetCapability:
-        g_debug ("processing TPM2_CC_GetCapability");
-        response = get_cap_gen_response (resmgr, command);
+        if (!tpm2_command_has_auths(command)) {
+            g_debug ("processing TPM2_CC_GetCapability");
+            response = get_cap_gen_response (resmgr, command);
+        }
         break;
     default:
         break;
```

2022-10-21 16:56 UTC, williamcroberts requested changes

2022-10-21 16:56 UTC, williamcroberts commented on src/resource-manager.c
> +    switch (cc) {
Don't change this hunk, lets keep the patch as small as possible. and not modify the switch at all.

2022-10-21 17:02 UTC, williamcroberts approved these changes

2022-10-21 17:03 UTC, williamcroberts commented
@whooo we should add a test that does that code snippet to ensure we don't break anything?

2022-10-21 17:55 UTC, whooo commented
> @whooo we should add a test that does that code snippet to ensure we don't break anything?

Do you have any flow in mind? Only thing I can think of is doing a unit test for `command_special_processing` and passing a Tpm2Command with a session

2022-10-21 18:03 UTC, williamcroberts commented
> > @whooo we should add a test that does that code snippet to ensure we don't break anything?
> 
> Do you have any flow in mind? Only thing I can think of is doing a unit test for `command_special_processing` and passing a Tpm2Command with a session

I was thinking an integration test where we start a session and add the handle, but I am OK with a unit test as well.

2022-10-21 18:19 UTC, whooo commented
> > > @whooo we should add a test that does that code snippet to ensure we don't break anything?
> > 
> > 
> > Do you have any flow in mind? Only thing I can think of is doing a unit test for `command_special_processing` and passing a Tpm2Command with a session
> 
> I was thinking an integration test where we start a session and add the handle, but I am OK with a unit test as well.

I'll look into creating a integration test which test with an audit session and one which tests with a password session, just need to get familiar with SAPI again

2022-10-21 18:21 UTC, williamcroberts commented
> > > > @whooo we should add a test that does that code snippet to ensure we don't break anything?
> > > 
> > > 
> > > Do you have any flow in mind? Only thing I can think of is doing a unit test for `command_special_processing` and passing a Tpm2Command with a session
> > 
> > 
> > I was thinking an integration test where we start a session and add the handle, but I am OK with a unit test as well.
> 
> I'll look into creating a integration test which test with an audit session and one which tests with a password session, just need to get familiar with SAPI again

Their is start_auth_session in common code for testing. It sets up an encrypted session if you need some reference code.

2022-10-21 22:44 UTC, whooo commented
Simple integration test added, I only added checks for failure with a password session and the success with an audit session, but don't verify the audit session

2022-10-24 17:20 UTC, williamcroberts approved these changes

2022-10-25 13:52 UTC, merged