Add file context entry for /usr/bin/tpm2-abrmd
tpm2-software/tpm2-abrmd pull request #846
Opened 2024-07-15 13:07 UTC by zpytela

To comply with the "Unify bin and sbin" Fedora Change [1], file equivalency for the /bin, /sbin, and /usr/sbin paths are now set in selinux-policy to /usr/bin.
This requires follow-up changes in DSP modules, too.

[1] https://fedoraproject.org/wiki/Changes/Unify_bin_and_sbin

2024-08-13 08:45 UTC, ca-hu commented
any updates here? this is breaking the tpm2-abrmd.service on systems with selinux enabled

see https://bugzilla.suse.com/show_bug.cgi?id=1229047

2024-11-20 20:21 UTC, williamcroberts approved these changes

2024-11-20 20:22 UTC, williamcroberts requested changes
You need to sign off your changes @zpytela

2024-11-20 22:01 UTC, zpytela commented
Signed, sorry that I missed the original request.

Also note this change is temporary until the actual change is made and may be handled in a different way for different supported releases.

2024-11-21 14:32 UTC, williamcroberts approved these changes

2025-09-15 13:39 UTC, kkaarreell commented
Hello, could you please fix this issue. It is opened for >1 year already.

2025-09-15 14:35 UTC, williamcroberts commented
Yes, I can look at this, I need to get the CI working as well.

2025-10-29 20:07 UTC, merged